# Config file for automatic build at travis-ci.org

language: python
python:
  - 3.8
  - 3.7
  - 3.6

jobs:
  include:
    # perform a linux build
    - services: docker
    # perform a linux ARMv8 build
    - services: docker
      arch: arm64
    # perform a linux PPC64LE build
    - services: docker
      arch: ppc64le
    # perform a linux S390X build
    - services: docker
      arch: s390x
    # and a mac build
    - os: osx
      language: shell


install:
  - python3 -m pip install cibuildwheel==1.6.1

script:
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse