# Config file for automatic build at travis-ci.org

language: python

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx
      language: shell


install:
  - python3 -m pip install cibuildwheel==1.6.1

script:
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse

env:
  global:
    - CIBW_BUILD=cp36-*

